# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e3663fe9ae46376f1c52fb1962f426fd19dab13d44cd3de53b3c4bede72828c0921e687028c313730ef805dfd8ac9bd8fb09cf6ba82db6c11c30d8bd4ad92d6

test:
  secret_key_base: 56e8fc91601fc87805e8a28144cf61aa8362fa5f1bdd68ab7bb7e52ad763c025d4c6c312a517d024cedc0db194aa3c9a59cd110b8847a5e648d9dbea00db1e81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
